// Generated by https://quicktype.io

/* The `export interface Product` is defining a TypeScript interface called `Product`. An interface in
TypeScript is a way to define the shape or structure of an object. In this case, the `Product`
interface has several properties such as `id`, `title`, `price`, `description`, `category`, and
`image`, which are all of specific types (`number` or `string`). Additionally, it has an optional
property `rating` of type `Rating`, which is another interface defined in the code. */
export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating?: Rating;
}

/* The `export interface Rating` is defining a TypeScript interface called `Rating`. An interface in
TypeScript is a way to define the shape or structure of an object. In this case, the `Rating`
interface has two properties: `rate` which is a number, and `count` which is also a number. */
export interface Rating {
  rate: number;
  count: number;
}
